sudo: required
services:
  - docker

before_install:
  - docker build -t multi-docker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run multi-docker/react-test npm run test

after_success:
  - docker build -t muhammedkamel/multi-client ./client
  - docker build -t muhammedkamel/multi-nginx ./nginx
  - docker build -t muhammedkamel/multi-server ./server
  - docker build -t muhammedkamel/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push muhammedkamel/multi-client
  - docker push muhammedkamel/multi-nginx
  - docker push muhammedkamel/multi-server
  - docker push muhammedkamel/multi-worker