version: '3'
services:
  nginx:
    image: 'complex/nginx'
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4000:80'
  postgres:
    image: 'complex/postgres'
    container_name: 'postgres'
    image: 'postgres:latest'
  redis:
    image: 'complex/redis'
    container_name: 'redis'
    image: 'redis:latest'
  api:
    image: 'complex/api'
    container_name: 'api'
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    image: 'complex/client'
    container_name: 'client'
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    image: 'complex/worker'
    container_name: 'worker'
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379